### ISSUE TITLE
Strange name/colour stripping

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#102]
![image](https://user-images.githubusercontent.com/1111522/27529815-4e65411a-5a99-11e7-8823-6d16a7503124.png)

Notice Rator81 in blue in the screenshot above - His name the appears as 87b4 In-game

His full name is: ^#004bff;Rator81^reset; though

**Comment by medeor413** [comment]
The regex matching names doesn't appear to be incorrect. The other possible scenario in which a user is assigned a randomized username is if the player changes their character name, and after filtering, the new name matches an existing name. Has there been a player by the name of Rator81 on the server before?

**Comment by ren-kun** [comment]
No this is the only rator81

**Comment by medeor413** [comment]
I can't think of any other reason that this would happen. For now, just /nick the player to the correct name. I'll come back and take a more in-depth look at this issue later.

**Comment by ren-kun** [comment]
![image](https://user-images.githubusercontent.com/1111522/27626220-99012210-5c2a-11e7-9ba2-886afcd7c7d8.png)

![image](https://user-images.githubusercontent.com/1111522/27626230-a1863a24-5c2a-11e7-8aaf-69f6d64cb5a0.png)

full name: ^#FF7FFF;R^#FF9BFF;e^#FFB2FF;m^#FFC6FF;i^#FFAAFF;^shadow;

Can't nick her to "remi" as the error is "there is already a user with this name"

**Comment by medeor413** [comment]
Can you /whois Remi?

**Comment by ren-kun** [comment]
Yes I can /whois remi - Brings up a player who is not online. 

/nick needed to the /who name appearing on chat

**Comment by medeor413** [comment]
It looks like the issue with Remi is indeed the thing I mentioned earlier. Can you also /whois Rator81 to be sure?

**Comment by medeor413** [comment]
Should be fixed with da55d3882bd7201e2b65fac7d70d7b7c1b2e0a39.
