### ISSUE TITLE
Discord bot going afterline after a while

### ISSUE THREAD

**Issue by thakyZ** [StarryPy/StarryPy3k#131]
My discord bot keeps going offline after a while and I cannot figure out what is causing it. I have provided logs, and I should mention at the end of the logs is when I restarted StarryPy.
https://gist.github.com/ccc3ef2532d50e11e452fd05bc1fb720

**Comment by medeor413** [comment]
This is unfortunately an issue with the Discord library we're using (discord.py). They've fixed it in the rewrite, but unfortunately that's still alpha so not really suitable for use yet, and backwards-incompatible as well. This'll get fixed when discord.py releases their rewrite.
