### ISSUE TITLE
Starbound 1.4

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#137]
Having troubles using Starry and SB1.4 together, such as it Doesn't detect admins.

**Comment by kharidiron** [comment]
Not to be assy, but we need more to go on than that - it is working for our current server (sbreddit), which implies either an edge-case that wasn't addressed or a misconfiguration. Can you provide the debug log, specific errors, or anything of that sort?

**Comment by ren-kun** [comment]
Apologies!  Ill be adding more information.

From the logs, A user tries to connect but is unable to connect to the server. Im not sure how the behavior happened but here is a snippet. 


```
2019-06-21 23:12:08 - DEBUG - starrypy # Initializing connection.
2019-06-21 23:12:08 - INFO - starrypy # Received connection from 187.254.110.151
2019-06-21 23:12:08 - DEBUG - starrypy # New connection established.
2019-06-21 23:13:06 - DEBUG - starrypy # Initializing connection.
2019-06-21 23:13:06 - INFO - starrypy # Received connection from 187.254.110.151
2019-06-21 23:13:06 - DEBUG - starrypy # New connection established.
```

I get a Join Failed! error

While I do a netstat -peant 

`
tcp        0      0 54.39.28.26:21025       45.127.94.8:61128       CLOSE_WAIT  1000       675752326   4343/python3.5
tcp        0      0 54.39.28.26:21025       181.169.135.26:49972    CLOSE_WAIT  1000       675478560   4343/python3.5
tcp        0      0 54.39.28.26:21025       187.254.110.151:10108   CLOSE_WAIT  1000       675428466   4343/python3.5
tcp        0      0 54.39.28.26:21025       45.127.94.8:61048       CLOSE_WAIT  1000       675734623   4343/python3.5
tcp        0      0 54.39.28.26:21025       187.254.110.151:63860   CLOSE_WAIT  1000       675590248   4343/python3.5
tcp        0      0 54.39.28.26:21025       162.231.153.1:52973     CLOSE_WAIT  1000       675769037   4343/python3.5
tcp6       0      0 :::21025 `

I notice that the ports are in a close_wait status

If you require more information Im happy to supply them.
