### ISSUE TITLE
Error starting Discord bot : login() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by copyrat90** [StarryPy/StarryPy3k#139]
Hi, I'm setting my new server on Ubuntu 16.04 with Python 3.5.7 and discord.py 1.2.3
Everytime I start up StarryPy3k with discord bot turned on, I got this same error.

> Traceback (most recent call last):
  File "/.../StarryPy3k/plugins/discord_bot.py", line 218, in start_bot
    yield from self.login(self.token, loop=self.loop)
TypeError: login() got an unexpected keyword argument 'loop'
[debug.log](https://github.com/StarryPy/StarryPy3k/files/3348461/debug.log)

I've also tested this on Ubuntu 18.04 with Python 3.6.8 and discord.py 1.2.3, but got the same error.

I once thought it has something to do with discord.py version changes, but looking through APIs for other versions, I cannot find the version which uses 'loop' as a keyword argument of discord.Client.login().

**Comment by medeor413** [comment]
The Discord bot module is built for <1.0 versions of discord.py, and the requirements.txt has not been updated to reflect this. Try using the last <1.0 version of discord.py?

**Comment by copyrat90** [comment]
The issue has been solved after I installed discord.py 0.16.12. Thanks!
But I'll leave this Issue opened until the DISCORD_BOT_SETUP.md is updated.

**Comment by KyeTheHuskyPup** [comment]
where and how do I install discord.py 0.16.12

**Comment by thakyZ** [comment]
run these commands to get an older version:
```
pip uninstall discord.py
pip install discord.py==0.16.12 --user
```
