### ISSUE TITLE
starrypy.plugin.discord_bot # Couldn't get staff channel! Reports will be sent to the main channel.

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#140]
`starrypy.plugin.discord_bot # Couldn't get staff channel! Reports will be sent to the main channel.`
`2020-07-31 05:24:09 - WARNING - discord.gateway # We have stopped responding to the gateway.`

The bot no longer works with the latest discord API. Downgrading its per-requisites no longer work.

**Comment by medeor413** [comment]
Should be fixed with #150
