### ISSUE TITLE
Provide official docker builds

### ISSUE THREAD

**Issue by evonzee** [StarryPy/StarryPy3k#151]
With my last PR I included a github action to build and push docker images to Dockerhub.  To do so, you need three repository secrets:

- DOCKERHUB_IMAGE: the name of the repository on Dockerhub.  For example, base10/starrypy3k
- DOCKERHUB_USERNAME: the username to use to login to Dockerhub
- DOCKERHUB_TOKEN: a token created in the security settings section of the aforementioned Dockerhub username

With these settings, Github will create and push builds of any branch.  If you tag your releases with semver tags (vx.y.z) it'll also tag them for you as x, x.y, and x.y.z.  Otherwise, it'll just tag with branch names.

Would be great to use this to provide official images for users who want to run in Docker but don't need or want to mess around with Python versions/modules/etc.

**Comment by medeor413** [comment]
Should now be available under [medeor/starrypy3k](https://hub.docker.com/repository/docker/medeor/starrypy3k/general).
