### ISSUE TITLE
Compatible 1.0 ?

### ISSUE THREAD

**Issue by roccosette** [StarryPy/StarryPy3k#25]
Is compatible 1.0 ? I had bugs when i launch it on 1.0

**Comment by Usiemon** [comment]
Try this branch instead. It's 80 commits ahead as of 2016/8/1, and works on my Starbound 1.0.3 server.
https://github.com/kharidiron/StarryPy3k/

**Comment by roccosette** [comment]
He works, but the command tp doesn't exist anymore ?

**Comment by kharidiron** [comment]
No, I have not yet reimplemented everything from the old starrypy. There is a lot of code that needs to be ported over, and with a whole new backend, it take a bit of time to make it all work.

**Comment by kharidiron** [comment]
StarryPy3K 1.0 has been migrated from my branch to here... and is compatible with Starbound 1.1.1.

Teleport is still not implemented... I will open that as its own (new) issue.
