### ISSUE TITLE
Ban/unban issue

### ISSUE THREAD

**Issue by kharidiron** [StarryPy/StarryPy3k#33]
_From @ren-kun on September 23, 2016 11:24_

Concerning the un-ban command.  If you unban via IP, the next reboot, the person is banned again.  You must unban via the original name that was banned.

_Copied from original issue: kharidiron/StarryPy3k#57_

**Comment by ren-kun** [comment]
I'm not sure if i should make a new issue but here it is:

But if you Ban by name, they're cleared after reboot.

**Comment by medeor413** [comment]
This is actually a symptom of #42.
