### ISSUE TITLE
Add "maintenance" mode - reject new player connections

### ISSUE THREAD

**Issue by kharidiron** [StarryPy/StarryPy3k#37]
_From @dopeghoti on August 6, 2016 22:5_

I prefer not to kick players off of my server if I don't have to, just to upgrade Starbound or the proxy.

It would be helpful to add an owner or admin command to tell StarryPy to no longer accept new player connections until either told otherwise or it is restarted.  That way, server admins can flip this switch, and when the last connected players leave of their own volition, the service(s) can be updated and restarted.

Bonus points for either or both of giving a configurable message shown to rejected clients, or for managing the MOTD and in-game broadcasts.

_Copied from original issue: kharidiron/StarryPy3k#38_

**Comment by kharidiron** [comment]
This is not an immediately-easy thing to implement well. I'm going to put it off for how, but I'll keep it in the queue.

**Comment by kharidiron** [comment]
_From @ren-kun on August 14, 2016 6:7_

Perhaps instead, you make a maintenance mode for a planet? This could tie into planet protection. 

In essence you could block access to a world you need to work on (Perhaps a spawn or hub) and players can still connect and do their own thing.

**Comment by medeor413** [comment]
Now that this is implemented, this issue can be closed.
