### ISSUE TITLE
Prevent/remove the  use of  " ^ " and other non english characters

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#41]
It's impossible to do a /who or /kick or /ban on names with special characters.

Also users going around making colors via star-cheat are filling up the debug log.

**Comment by medeor413** [comment]
Color codes and non-ASCII characters have been filtered from StarryPy's aliases for a while, and most commands use those aliases instead of raw names, although it does appear that /ban still uses raw names still, so that will need to be fixed.
