### ISSUE TITLE
Vehicle bypass planets protection

### ISSUE THREAD

**Issue by sprthomas** [StarryPy/StarryPy3k#47]
Hello,
so basically, some vehicles (like XS mech mod for example) can destroy blocks with their weapons, even if the planets was protected.
Is there a way to fix this?
thanks.

**Comment by ren-kun** [comment]
Also, Particle grenades, Ronin mech, Hyperion mostly from Frackin can bypass it,

Is it possible to make a white-list/black-lists to control these issues? Kind of like the race controller?

**Comment by medeor413** [comment]
Unfortunately vehicles are server side entities, which means that they don't have to go through the wrapper. The way StarryPy functions, we can only block things that are done on the client's end and sent to the server.

**Comment by ren-kun** [comment]
Oh! I would like to inquire more. 

On a modded server, with mismatch toggled (Which means the user and server must have the EXACT same mods and in the same order etc) Which could technically mean you could stop the damage as its also player side?

**Comment by medeor413** [comment]
What I mean is, when it comes to vehicles, all of the interactions, including tile damage, are calculated server-side, and the results are sent to clients. StarryPy can only interfere when the client does the calculations and sends them to the server, so I'm fairly certain there's nothing we can do here. I would recommend patching the mods you're using to not do block damage.

**Comment by sprthomas** [comment]
Is that possible to disable the use of a certain item with StarryPy?
That way, we could disable a vehicle controller on a protected planet.

**Comment by medeor413** [comment]
Disallowing spawning vehicles is potentially doable, I'll look into it.

**Comment by ren-kun** [comment]
Yes please
