### ISSUE TITLE
Is /poi PLANET_NAME failing to work?

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#53]
Hey everyone,

/poi - works as a command

but when trying to do /poi NAME (to force the ship to go somewhere)

It doesn't work. Did i perhaps set something wrong:?

**Comment by teihoo** [comment]
Long while ago I created the guide for commands - this was with old StarryPy, since Dropbox will be removing public folder links soon, maybe someone should grab it and update/use for current version?
Here is the link: https://dl.dropboxusercontent.com/u/13248066/Starbound/StarryPy_ingame_commands.pdf

And for /poi NAME to work, administrator should set /poi_set NAME first, as far as I remember, but could aswell be broken in current release.

**Comment by ren-kun** [comment]
Well TBH I can't promote it to a player. Says poi isn't a role.

Also it seems only the owner can use it to move the ship. Other users receive no errors.

**Comment by teihoo** [comment]
The idea of PoI's were that owners / admins can designate some planets as hubs - in this regard any player even guest can use an admin defined Point of Interest.

**Comment by ren-kun** [comment]
I think I didn't express my self properly.

-poi list / destination is set
-guests can't use POI on their ship, doesn't move the ship
-can't grant the role either way

**Comment by teihoo** [comment]
Then it's probably a permission bug. I'm not actively working on this anymore, sry was just trying to help if its a usability issue. Hope one of the guys will take a look at it soon. (and you're right about role, should be available to use for any role - no assigning)

**Comment by ren-kun** [comment]
@teihoo Thanks for your help though :)!

**Comment by ren-kun** [comment]
/poi may have a permission issue. admins and above can fly with POI,  but not guests.

/grant poi -user rank- gives the following error

"Invalid literal for int() with base 10:  Guest"

And sometimes it says

"Invalid Command"

**Comment by ren-kun** [comment]
Sometimes it works, sometimes it doesnt...

**Comment by medeor413** [comment]
Sorry, yeah, the ship detection on /spawn and /poi was bugged. I've got a fix for this in [my pull request](https://github.com/StarryPy/StarryPy3k/pull/57), which will be merged soon.

**Comment by ren-kun** [comment]
OK thanks :)

**Comment by medeor413** [comment]
This should be fixed with #57.

**Comment by ren-kun** [comment]
Hello! @medeor413 

Only T1 ships and higher can POI - Which isn't a bad thing.
