### ISSUE TITLE
How to edit which user groups can do what commands?

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#55]
Is it possible to change what user group can do which commands?

Perhaps I want POI to be registered and higher?

**Comment by medeor413** [comment]
Unfortunately right now all command permissions are defined in the code. Making permissions editable from a simple config file is on the roadmap, but for now you can change the role required to use a command by editing or adding the line `role=Guest` to the `@Command` decorator of the command function.

**Comment by ren-kun** [comment]
Hello!

I'm sorry but I, don't understand what you mean, in regards to the steps you have provided me with.

**Comment by medeor413** [comment]
This is now implemented with #73.
