### ISSUE TITLE
 The /report does not show in other chat tabs

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#61]
Is it possible to make /report high priority and appear in local & other chat tabs?

If moderators and higher can't see it in all chat tabs then there's a possibility of a delay for staff to respond when in their current tab

**Comment by medeor413** [comment]
This could probably be done relatively easily, I'll try and make it happen.

**Comment by medeor413** [comment]
On further inspection, there isn't actually a chat mode that can send to all channels. So, this isn't really possible. I would suggest that you use a chat mod that displays all messages in any tab.

**Comment by medeor413** [comment]
Unfortunately, there's no chat mode that broadcasts to all tabs, so I can't really do anything about this. I'd recommend you use a chat mod that allows all messages to show in any tab.

**Comment by ren-kun** [comment]
Ok thanks medeor
