### ISSUE TITLE
-/motd

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#62]
Does the MOTD have a time parameter? Not sure if it pops up enough.

Or perhaps when an admin uses /motd it forces it to all users with a 5 minute cool down?

**Comment by medeor413** [comment]
MotD delays by one second currently, this might be a bit too short.

**Comment by ren-kun** [comment]
Hrmm Because sometimes the MOTD doesn't show up (according to some users)

It would be a cool idea if we can get it to push on demand as well. Unless the broadcast command is what its for?

**Comment by medeor413** [comment]
This should be fixed with e4343d415cdf9c12be450317831e8b388ab996aa, reopen this if not.
