### ISSUE TITLE
Adding own roles and shuffling commands

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#68]
Hello, I am aware that a way to move commands around to different roles is coming.

But is there anything happening about making our own roles? (for example a donator role) 

In regards to both what do you think the ETA can be?

**Comment by medeor413** [comment]
Yup, you'll be able to define as many roles as you like. I can't give a specific ETA, but it's my current project, so not too much longer.

**Comment by medeor413** [comment]
This is now implemented with #73.
