### ISSUE TITLE
Granting a user a command resets their role

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#71]
Hello,

I have a user who I gave a command to, as it isn't part of their role. But in doing so it would reset their role to a guest (if they had one previously)

**Comment by medeor413** [comment]
Yep, that's a result of the quick fix that was used to allow demoting users. Not gonna fix this, since the current system is getting replaced anyways.

**Comment by ren-kun** [comment]
Ok thanks Medeor!

Best of luck for it!

**Comment by medeor413** [comment]
Fixed via replacement of the system in #73.
