### ISSUE TITLE
Players not fully disconnecting when leaving server

### ISSUE THREAD

**Issue by thakyZ** [StarryPy/StarryPy3k#75]
When someone with a name joins a server they cannot join again with a different character with the same name.
Here is the bug log:
https://pastebin.com/1tkr5wiZ

**Comment by GermaniumSystem** [comment]
As far as I know, this is by design. StarryPy3k registers the name to the specific player's UUID and will only allow that UUID to use the name from then on. This appears to be mainly for preventing impersonation, but may have been much more important in the past.

**Comment by medeor413** [comment]
Yep, that is [definitely intentional.](https://github.com/StarryPy/StarryPy3k/issues/8)
