### ISSUE TITLE
Custom ranks/roles cannot log back in:  Unotherised error

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#82]
Hello,

Lets say i have a custom role. I grant them it, but they cannot log back in after logging out.

Its the unauthorized error when a user doesn't has an account.

Now the error on the log is " Player with privileged UUID -uuid- FAILED to authenticate as ' '!

**Comment by medeor413** [comment]
Players with roles above the minimum priority set in basic auth need to log in with an account. You can give these users an account or raise the minimum priority in the basic auth config.

**Comment by ren-kun** [comment]
Hello,

You are referring to the " "staff_priority": 100," correct?

**Comment by medeor413** [comment]
That's the one.

**Comment by ren-kun** [comment]
Thanks
